branch-defaults:
  master:
    environment: dBot-dev
global:
  application_name: d.Bot
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
